2025-05-27 10:06:56,581 - root - ERROR - Error creating database tables: Foreign key associated with column 'user.created_by' could not find table 'users' with which to generate a foreign key to target column 'id'
2025-05-27 10:07:48,771 - root - ERROR - Error creating database tables: Foreign key associated with column 'user.modified_by' could not find table 'users' with which to generate a foreign key to target column 'id'
2025-06-05 07:40:40,637 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'media_files'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f3249325090>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 07:42:04,319 - app.db.session - ERROR - Database session error: app.models.article.Article() argument after ** must be a mapping, not ArticleCreate
2025-06-05 08:11:17,544 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-05 09:08:32,234 - app.db.session - ERROR - Database session error: 
2025-06-05 09:15:41,858 - app.db.session - ERROR - Database session error: 
2025-06-05 09:17:10,290 - app.db.session - ERROR - Database session error: 
2025-06-05 09:19:29,067 - app.db.session - ERROR - Database session error: 
2025-06-05 09:21:11,156 - app.db.session - ERROR - Database session error: 
2025-06-05 09:23:44,088 - app.db.session - ERROR - Database session error: 
2025-06-05 09:24:58,114 - app.db.session - ERROR - Database session error: object of type 'int' has no len()
2025-06-05 09:29:55,079 - app.db.session - ERROR - Database session error: (psycopg2.errors.UndefinedColumn) column "updated_at" of relation "media_file" does not exist
LINE 1: INSERT INTO media_file (filename, file_type, url, updated_at...
                                                          ^

[SQL: INSERT INTO media_file (filename, file_type, url, updated_at) VALUES (%(filename)s, %(file_type)s, %(url)s, %(updated_at)s) RETURNING media_file.id]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-05 09:31:08,113 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ชื่อ-บทความ-สำหรับ-url) already exists.

[SQL: INSERT INTO article (title, slug, content, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ชื่อบทความ', 'slug': 'ชื่อ-บทความ-สำหรับ-url', 'content': 'เนื้อหาเริ่มต้น {{media_0}} ต่อเนื้อหา {{media_1}} จบเนื้อหา', 'created_at': datetime.datetime(2025, 6, 5, 9, 31, 8, 111378), 'updated_at': datetime.datetime(2025, 6, 5, 9, 31, 8, 111380)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-05 09:36:14,075 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:37:05,671 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:44:50,807 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[0, 1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '[0, 1]', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:58:50,664 - app.db.session - ERROR - Database session error: 
2025-06-05 10:00:55,278 - app.db.session - ERROR - Database session error: 
2025-06-05 10:02:55,153 - app.db.session - ERROR - Database session error: 
2025-06-05 10:05:39,636 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:06:32,694 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:06:40,642 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:08:20,051 - app.db.session - ERROR - Database session error: 
2025-06-05 10:08:45,987 - app.db.session - ERROR - Database session error: 
2025-06-05 10:09:10,960 - app.db.session - ERROR - Database session error: 
2025-06-05 10:37:46,160 - app.db.session - ERROR - Database session error: 
2025-06-05 10:37:52,058 - app.db.session - ERROR - Database session error: 
2025-06-06 03:35:10,661 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:20,905 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:27,047 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:53,461 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:37:58,092 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:38:22,108 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:39:43,476 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:39:53,019 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:41:28,198 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'media_files'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f40c2966e50>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-06 03:44:43,880 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-06 03:48:24,208 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 03:48:27,751 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ttttt2) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'tttt2', 'slug': 'ttttt2', 'content': 'tttt2', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 6, 3, 48, 27, 749768), 'updated_at': datetime.datetime(2025, 6, 6, 3, 48, 27, 749771)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 03:49:02,752 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 03:50:17,388 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:02:05,429 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:03:13,622 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:04:51,527 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:07:26,604 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:08:39,186 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:08:53,904 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:10:47,135 - app.db.session - ERROR - Database session error: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "article_view_log" violates not-null constraint
DETAIL:  Failing row contains (1, 2, null, null, 172.24.0.1, 2025-06-06 04:10:47.128187).

[SQL: INSERT INTO article_view_log (article_id, user_id, user_session_id, ip_address, viewed_at) VALUES (%(article_id)s, %(user_id)s, %(user_session_id)s::UUID, %(ip_address)s, %(viewed_at)s) RETURNING article_view_log.id]
[parameters: {'article_id': 2, 'user_id': None, 'user_session_id': None, 'ip_address': '172.24.0.1', 'viewed_at': datetime.datetime(2025, 6, 6, 4, 10, 47, 128187)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 04:12:03,035 - app.db.session - ERROR - Database session error: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "article_view_log" violates not-null constraint
DETAIL:  Failing row contains (2, 2, null, null, 172.24.0.1, 2025-06-06 04:12:03.029236).

[SQL: INSERT INTO article_view_log (article_id, user_id, user_session_id, ip_address, viewed_at) VALUES (%(article_id)s, %(user_id)s, %(user_session_id)s::UUID, %(ip_address)s, %(viewed_at)s) RETURNING article_view_log.id]
[parameters: {'article_id': 2, 'user_id': None, 'user_session_id': None, 'ip_address': '172.24.0.1', 'viewed_at': datetime.datetime(2025, 6, 6, 4, 12, 3, 29236)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 04:22:10,325 - app.db.session - ERROR - Database session error: 
2025-06-06 04:22:24,974 - app.db.session - ERROR - Database session error: 
2025-06-09 10:47:37,221 - app.db.session - ERROR - Database session error: [{'type': 'missing', 'loc': ('body', 'category_ids'), 'msg': 'Field required', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}]
2025-06-09 10:48:28,678 - app.db.session - ERROR - Database session error: [{'type': 'missing', 'loc': ('body', 'category_ids'), 'msg': 'Field required', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}]
2025-06-09 10:50:47,364 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:50:50,076 - app.db.session - ERROR - Database session error: 'NoneType' object is not iterable
2025-06-09 10:52:17,812 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(gggggg) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ggggggg', 'slug': 'gggggg', 'content': 'gggggg', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 9, 10, 52, 17, 808955), 'updated_at': datetime.datetime(2025, 6, 9, 10, 52, 17, 808959)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-09 10:57:17,295 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:57:35,206 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1,2]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:58:06,797 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 11:00:18,694 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 11:00:33,773 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-10 09:19:37,144 - app.db.session - ERROR - Database session error: MinIOArticleService.upload_article_file() missing 1 required positional argument: 'file'
2025-06-10 09:19:52,759 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ttttt2) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ttttt2', 'slug': 'ttttt2', 'content': 'ttttttt2', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 10, 9, 19, 52, 754862), 'updated_at': datetime.datetime(2025, 6, 10, 9, 19, 52, 754864)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-10 09:20:01,687 - app.db.session - ERROR - Database session error: MinIOArticleService.upload_article_file() missing 1 required positional argument: 'file'
2025-06-10 09:20:18,560 - app.db.session - ERROR - Database session error: MinIOArticleService.upload_article_file() missing 1 required positional argument: 'file'
2025-06-10 09:24:52,299 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ttttt222) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ttttt222', 'slug': 'ttttt222', 'content': 'ttttttt222', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 10, 9, 24, 52, 297501), 'updated_at': datetime.datetime(2025, 6, 10, 9, 24, 52, 297503)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-10 09:25:00,225 - app.db.session - ERROR - Database session error: MinIOArticleService.upload_article_file() missing 1 required positional argument: 'file'
2025-06-10 09:27:44,910 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ttttt2223) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ttttt2223', 'slug': 'ttttt2223', 'content': 'ttttttt2223', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 10, 9, 27, 44, 907903), 'updated_at': datetime.datetime(2025, 6, 10, 9, 27, 44, 907905)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-10 09:27:57,062 - app.db.session - ERROR - Database session error: MinIOArticleService.__init__() missing 1 required positional argument: 'self'
2025-06-10 09:35:45,982 - app.db.session - ERROR - Database session error: 
2025-06-10 09:36:14,515 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(yuk55544) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'th55544', 'slug': 'yuk55544', 'content': 'ghj5554', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 10, 9, 36, 14, 513821), 'updated_at': datetime.datetime(2025, 6, 10, 9, 36, 14, 513825)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-12 03:46:01,037 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'list_type', 'loc': ('response', 'related_articles'), 'msg': 'Input should be a valid list', 'input': '{}', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}

2025-06-12 03:48:24,032 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ten) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, created_at, updated_at, related_articles) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(created_at)s, %(updated_at)s, %(related_articles)s) RETURNING article.id]
[parameters: {'title': 'ten', 'slug': 'ten', 'content': 'ten', 'view_count': 0, 'status': 'public', 'created_at': datetime.datetime(2025, 6, 12, 3, 48, 24, 29474), 'updated_at': datetime.datetime(2025, 6, 12, 3, 48, 24, 29476), 'related_articles': []}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-12 03:48:36,197 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'list_type', 'loc': ('response', 'related_articles'), 'msg': 'Input should be a valid list', 'input': '{}', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}

2025-06-12 03:56:28,295 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'list_type', 'loc': ('response', 'related_articles'), 'msg': 'Input should be a valid list', 'input': '{}', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}

2025-06-12 03:58:21,117 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'list_type', 'loc': ('response', 'related_articles'), 'msg': 'Input should be a valid list', 'input': '[]', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}

2025-06-12 04:12:46,523 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-12 04:24:53,170 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-12 04:25:50,211 - app.db.session - ERROR - Database session error: 
2025-06-12 04:25:55,365 - app.db.session - ERROR - Database session error: You must set the config attribute `from_attributes=True` to use from_orm
2025-06-12 04:26:45,252 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-12 09:29:54,192 - app.db.session - ERROR - Database session error: 
2025-06-12 09:30:09,029 - app.db.session - ERROR - Database session error: 
2025-06-12 09:31:21,540 - app.db.session - ERROR - Database session error: 
2025-06-12 09:31:39,676 - app.db.session - ERROR - Database session error: 
2025-06-12 09:31:56,494 - app.db.session - ERROR - Database session error: 
2025-06-12 09:32:05,531 - app.db.session - ERROR - Database session error: 
2025-06-12 09:33:11,902 - app.db.session - ERROR - Database session error: create_article_with_categories() takes 2 positional arguments but 3 were given
2025-06-12 09:35:38,462 - app.db.session - ERROR - Database session error: 'ArticleCreate' object has no attribute 'tags'
2025-06-12 09:36:27,010 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-12 09:40:31,865 - app.db.session - ERROR - Database session error: 
2025-06-12 09:40:40,784 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-12 09:41:47,314 - app.db.session - ERROR - Database session error: 
2025-06-12 09:41:50,986 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-12 09:54:45,198 - app.db.session - ERROR - Database session error: type object 'Tag' has no attribute 'name'
2025-06-12 09:56:15,725 - app.db.session - ERROR - Database session error: 2 validation errors:
  {'type': 'missing', 'loc': ('response', 'tags', 0, 'tagname'), 'msg': 'Field required', 'input': <app.models.article.Tag object at 0x7fef31873d50>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}
  {'type': 'model_attributes_type', 'loc': ('response', 'related_articles', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 1, 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-12 09:59:11,056 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(test) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'test', 'slug': 'test', 'content': 'test {Screenshot (371)}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 12, 9, 59, 11, 52444), 'updated_at': datetime.datetime(2025, 6, 12, 9, 59, 11, 52448)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-12 09:59:31,324 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response', 'related_articles', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 1, 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-12 10:00:08,284 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response', 'related_articles', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 1, 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-12 10:23:43,599 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'embedded_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f8c1c5dab10>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}, {'type': 'list_type', 'loc': ('body', 'attached_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f8c1c5da250>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-12 10:24:51,811 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'embedded_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7ff6a180a390>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}, {'type': 'list_type', 'loc': ('body', 'attached_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7ff6a1809dd0>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-12 10:25:27,661 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'embedded_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f850a6f2350>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}, {'type': 'list_type', 'loc': ('body', 'attached_media'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f850a6f1d50>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-12 10:33:04,004 - app.db.session - ERROR - Database session error: 
2025-06-12 10:33:43,412 - app.db.session - ERROR - Database session error: 
2025-06-12 10:33:51,345 - app.db.session - ERROR - Database session error: 
2025-06-12 10:45:02,895 - app.db.session - ERROR - Database session error: 
2025-06-12 10:45:10,034 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(we) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'we', 'slug': 'we', 'content': 'we {Screenshot (371)}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 12, 10, 45, 10, 31038), 'updated_at': datetime.datetime(2025, 6, 12, 10, 45, 10, 31041)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 03:47:46,213 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'related_articles', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-13 03:54:29,210 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'related_articles'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'category_ids'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'value_error', 'loc': ('body', 'attached_media', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-13 03:59:18,324 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'related_articles'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'category_ids'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'value_error', 'loc': ('body', 'attached_media', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-13 03:59:51,397 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'related_articles'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'category_ids'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'value_error', 'loc': ('body', 'attached_media', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-13 04:00:04,682 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'related_articles', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'value_error', 'loc': ('body', 'attached_media', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-13 04:04:21,396 - app.db.session - ERROR - Database session error: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "["
LINE 1: ... (article_id, media_id, position) VALUES (13, 22, '[') RETUR...
                                                             ^

[SQL: INSERT INTO article_media (article_id, media_id, position) VALUES (%(article_id)s, %(media_id)s, %(position)s) RETURNING article_media.id]
[parameters: {'article_id': 13, 'media_id': 22, 'position': '['}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-13 04:05:55,356 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(kk) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'kk', 'slug': 'kk', 'content': 'kk {Screenshot (371)} kk {gg}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 13, 4, 5, 55, 352352), 'updated_at': datetime.datetime(2025, 6, 13, 4, 5, 55, 352354)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 04:06:24,135 - app.db.session - ERROR - Database session error: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "["
LINE 1: ... (article_id, media_id, position) VALUES (15, 24, '[') RETUR...
                                                             ^

[SQL: INSERT INTO article_media (article_id, media_id, position) VALUES (%(article_id)s, %(media_id)s, %(position)s) RETURNING article_media.id]
[parameters: {'article_id': 15, 'media_id': 24, 'position': '['}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-13 04:09:10,529 - app.db.session - ERROR - Database session error: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "["
LINE 1: ... (article_id, media_id, position) VALUES (16, 26, '[') RETUR...
                                                             ^

[SQL: INSERT INTO article_media (article_id, media_id, position) VALUES (%(article_id)s, %(media_id)s, %(position)s) RETURNING article_media.id]
[parameters: {'article_id': 16, 'media_id': 26, 'position': '['}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-13 04:10:01,621 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'embedded_media_positions'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-13 04:13:30,394 - app.db.session - ERROR - Database session error: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "["
LINE 1: ... (article_id, media_id, position) VALUES (17, 28, '[') RETUR...
                                                             ^

[SQL: INSERT INTO article_media (article_id, media_id, position) VALUES (%(article_id)s, %(media_id)s, %(position)s) RETURNING article_media.id]
[parameters: {'article_id': 17, 'media_id': 28, 'position': '['}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-13 04:13:34,253 - app.db.session - ERROR - Database session error: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "["
LINE 1: ... (article_id, media_id, position) VALUES (18, 30, '[') RETUR...
                                                             ^

[SQL: INSERT INTO article_media (article_id, media_id, position) VALUES (%(article_id)s, %(media_id)s, %(position)s) RETURNING article_media.id]
[parameters: {'article_id': 18, 'media_id': 30, 'position': '['}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-06-13 04:37:15,863 - app.db.session - ERROR - Database session error: 
2025-06-13 05:01:23,211 - app.db.session - ERROR - Database session error: (psycopg2.errors.ForeignKeyViolation) insert or update on table "article_category" violates foreign key constraint "article_category_category_id_fkey"
DETAIL:  Key (category_id)=(1) is not present in table "categories".

[SQL: INSERT INTO article_category (article_id, category_id) VALUES (%(article_id)s, %(category_id)s) RETURNING article_category.id]
[parameters: {'article_id': 1, 'category_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 06:28:31,622 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(cc12) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'cc12', 'slug': 'cc12', 'content': 'cc {Screenshot (371)}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 13, 6, 28, 31, 618287), 'updated_at': datetime.datetime(2025, 6, 13, 6, 28, 31, 618290)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 06:28:39,997 - app.db.session - ERROR - Database session error: 2 validation errors:
  {'type': 'missing', 'loc': ('response', 'attached_media', 0, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f508fc7ad50>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}
  {'type': 'missing', 'loc': ('response', 'attached_media', 1, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f508fc7b950>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}

2025-06-13 06:36:30,684 - app.db.session - ERROR - Database session error: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'embedded_media', 0, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f1f32353fd0>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}
  {'type': 'missing', 'loc': ('response', 'embedded_media', 1, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f1f32358b90>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}
  {'type': 'missing', 'loc': ('response', 'attached_media', 0, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f1f32353fd0>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}
  {'type': 'missing', 'loc': ('response', 'attached_media', 1, 'media'), 'msg': 'Field required', 'input': <app.models.article.MediaFile object at 0x7f1f32358b90>, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}

2025-06-13 06:49:20,203 - app.db.session - ERROR - Database session error: 
2025-06-13 07:01:26,515 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(ss12) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ss12', 'slug': 'ss12', 'content': 'ss {Screenshot (371)}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 13, 7, 1, 26, 513040), 'updated_at': datetime.datetime(2025, 6, 13, 7, 1, 26, 513043)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 07:11:18,408 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(ss1232) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ss12342', 'slug': 'ss1232', 'content': 'ss {Screenshot (371)}', 'view_count': 0, 'status': 'public', 'related_articles': '[1]', 'created_at': datetime.datetime(2025, 6, 13, 7, 11, 18, 404696), 'updated_at': datetime.datetime(2025, 6, 13, 7, 11, 18, 404700)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 07:25:10,433 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_article_slug"
DETAIL:  Key (slug)=(dfg) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, status, related_articles, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(status)s, %(related_articles)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'hhd', 'slug': 'dfg', 'content': None, 'view_count': 0, 'status': 'public', 'related_articles': '[]', 'created_at': datetime.datetime(2025, 6, 13, 7, 25, 10, 429608), 'updated_at': datetime.datetime(2025, 6, 13, 7, 25, 10, 429611)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-13 07:32:22,458 - root - ERROR - Error creating database tables: string index out of range
2025-06-16 05:00:43,781 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(หห) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'หห', 'slug': 'หห', 'content': 'หห {Screenshot (371)} หห {Screenshot (373)}', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 16, 5, 0, 43, 778543), 'updated_at': datetime.datetime(2025, 6, 16, 5, 0, 43, 778546)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-16 05:00:55,108 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(หห1) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'หห1', 'slug': 'หห1', 'content': 'หห {Screenshot (371)} หห {Screenshot (373)}', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 16, 5, 0, 55, 105874), 'updated_at': datetime.datetime(2025, 6, 16, 5, 0, 55, 105877)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-16 08:26:05,259 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:26:08,230 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:26:18,866 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:42:59,419 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:44:46,306 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:44:49,006 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 08:47:36,375 - root - ERROR - Error creating database tables: (psycopg2.errors.UndefinedObject) type "media_type_enum" does not exist
LINE 8:  media_type media_type_enum NOT NULL, 
                    ^

[SQL: 
CREATE TABLE article_media (
	id SERIAL NOT NULL, 
	article_id INTEGER, 
	filename TEXT NOT NULL, 
	file_type VARCHAR NOT NULL, 
	url TEXT NOT NULL, 
	media_type media_type_enum NOT NULL, 
	uploaded_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(article_id) REFERENCES article (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-16 09:00:03,866 - app.db.session - ERROR - Database session error: 'media_id' is an invalid keyword argument for ArticleMedia
2025-06-16 09:27:12,492 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(gg) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'gg', 'slug': 'gg', 'content': 'gg {Screenshot (371)}', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 16, 9, 27, 12, 488173), 'updated_at': datetime.datetime(2025, 6, 16, 9, 27, 12, 488176)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-16 09:33:24,274 - app.db.session - ERROR - Database session error: 'ArticleMedia' object has no attribute 'position'
2025-06-16 09:33:44,571 - app.db.session - ERROR - Database session error: 'ArticleMedia' object has no attribute 'position'
2025-06-16 09:34:18,924 - app.db.session - ERROR - Database session error: 'ArticleMedia' object has no attribute 'position'
2025-06-16 10:05:41,136 - app.db.session - ERROR - Database session error: 
2025-06-16 10:09:34,944 - app.db.session - ERROR - Database session error: 3 validation errors for ArticleCreate
tags
  Input should be a valid list [type=list_type, input_value='ไทย', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/list_type
hashtag
  Input should be a valid list [type=list_type, input_value='#ไทย', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/list_type
schedule
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 6, 20, 10, 0), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-06-16 10:13:17,809 - app.db.session - ERROR - Database session error: 1 validation error for ArticleCreate
schedule
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 6, 20, 10, 0), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-06-16 10:14:03,589 - app.db.session - ERROR - Database session error: 
2025-06-16 10:14:11,062 - app.db.session - ERROR - Database session error: 1 validation error for ArticleCreate
schedule
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 6, 20, 10, 0), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-06-16 10:15:31,745 - app.db.session - ERROR - Database session error: 1 validation error for ArticleCreate
schedule
  Input should be a valid string [type=string_type, input_value=datetime.datetime(2025, 6, 20, 10, 0), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-06-16 10:17:09,355 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-16 10:20:03,454 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-16 10:20:46,837 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-16 10:28:09,054 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-16 10:28:23,094 - app.db.session - ERROR - Database session error: 3 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response', 'tags', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 'ไทย', 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}
  {'type': 'model_attributes_type', 'loc': ('response', 'hashtag', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': '#wmp', 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}
  {'type': 'list_type', 'loc': ('response', 'status'), 'msg': 'Input should be a valid list', 'input': 'private', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}

2025-06-16 10:30:15,942 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(zz) already exists.

[SQL: INSERT INTO article (title, slug, status, tags, hashtag, content, schedule, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(status)s, %(tags)s::VARCHAR[], %(hashtag)s::VARCHAR[], %(content)s, %(schedule)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'zz', 'slug': 'zz', 'status': 'private', 'tags': ['ไทย'], 'hashtag': ['#wmp'], 'content': 'zz {user_5036458879_5db619fe-ed15-4f4b-9121-df5855293dbf}', 'schedule': datetime.datetime(2025, 6, 20, 10, 0), 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 16, 10, 30, 15, 938333), 'updated_at': datetime.datetime(2025, 6, 16, 10, 30, 15, 938336)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-16 10:30:26,206 - app.db.session - ERROR - Database session error: 3 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response', 'tags', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 'ไทย', 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}
  {'type': 'model_attributes_type', 'loc': ('response', 'hashtag', 0), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': '#wmp', 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}
  {'type': 'model_attributes_type', 'loc': ('response', 'status'), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 'private', 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-17 03:24:21,392 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 04:14:13,917 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 04:34:33,170 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(rra) already exists.

[SQL: INSERT INTO article (title, slug, status, tags, hashtag, content, start_date, end_date, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(status)s, %(tags)s::VARCHAR[], %(hashtag)s::VARCHAR[], %(content)s, %(start_date)s, %(end_date)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'rra', 'slug': 'rra', 'status': 'private', 'tags': ['thai', 'gg'], 'hashtag': ['#thsi', '#gg'], 'content': None, 'start_date': datetime.datetime(2025, 6, 20, 10, 0), 'end_date': datetime.datetime(2025, 6, 20, 18, 0), 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 17, 4, 34, 33, 167291), 'updated_at': datetime.datetime(2025, 6, 17, 4, 34, 33, 167293)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-17 04:55:12,819 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 04:55:21,484 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-17 04:56:24,698 - app.db.session - ERROR - Database session error: 'str' object has no attribute '_sa_instance_state'
2025-06-17 05:02:20,155 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 07:22:55,684 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 07:24:31,187 - app.db.session - ERROR - Database session error: 
2025-06-17 07:24:51,072 - app.db.session - ERROR - Database session error: 
2025-06-17 07:24:56,740 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(dd111) already exists.

[SQL: INSERT INTO article (title, slug, status, content, start_date, end_date, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(status)s, %(content)s, %(start_date)s, %(end_date)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'dd111', 'slug': 'dd111', 'status': 'private', 'content': None, 'start_date': None, 'end_date': None, 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 17, 7, 24, 56, 737415), 'updated_at': datetime.datetime(2025, 6, 17, 7, 24, 56, 737418)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-17 07:26:51,914 - app.db.session - ERROR - Database session error: 
2025-06-17 09:50:00,272 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 09:55:59,479 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 10:00:24,669 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 10:00:35,778 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 10:00:38,655 - app.db.session - ERROR - Database session error: 'NoneType' object is not iterable
2025-06-17 10:01:24,960 - app.db.session - ERROR - Database session error: 'NoneType' object is not iterable
2025-06-17 10:01:31,560 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-17 10:04:52,259 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'embedded_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}, {'type': 'value_error', 'loc': ('body', 'attached_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-18 03:39:44,248 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:52,350 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:52,747 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:52,919 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:53,079 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:53,226 - app.db.session - ERROR - Database session error: 
2025-06-18 03:39:53,382 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:09,800 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:35,858 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:56,273 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:56,626 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:56,815 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:56,993 - app.db.session - ERROR - Database session error: 
2025-06-18 03:41:57,148 - app.db.session - ERROR - Database session error: 
2025-06-18 03:43:30,054 - app.db.session - ERROR - Database session error: 
